made path split platform independent
Previously, the implementation for searching the $PATH variable split on
the ';' character. This does not in unixlike systems, causing a failure
to find the CMTK executable, or causing an exception:
    OSError: [Errno 63] File name too long
os.pathsep solves this problem